/// Renders a Proxy Auto-Config (PAC) script that sends only the given
/// `domains` (and their subdomains) through `proxy_host:proxy_port`;
/// everything else resolves to `DIRECT`, bypassing the proxy entirely.
pub fn render_pac(domains: &[String], proxy_host: &str, proxy_port: u16) -> String {
    // `serde_json::to_string` on a plain string produces a properly escaped
    // JS/JSON string literal — domains land here from local config today,
    // but this keeps a bad entry (an embedded quote/backslash) from being
    // able to break out of the string literal into executable PAC script
    // once domain lists can come from a pushed remote config (see
    // ROADMAP.md's cloud control plane phase).
    let entries = domains
        .iter()
        .map(|d| {
            let escaped = serde_json::to_string(&d.to_ascii_lowercase())
                .expect("string serialization cannot fail");
            format!("        {escaped}")
        })
        .collect::<Vec<_>>()
        .join(",\n");

    format!(
        r#"// Generated by agentctl - do not edit by hand, it will be overwritten.
// Routes only the listed AI-service domains (and their subdomains) through
// the local AI-SPM DLP agent; every other request goes DIRECT (not through us).
function FindProxyForURL(url, host) {{
    var targets = [
{entries}
    ];
    host = host.toLowerCase();
    for (var i = 0; i < targets.length; i++) {{
        var d = targets[i];
        if (host === d || (host.length > d.length + 1 && host.substring(host.length - d.length - 1) === "." + d)) {{
            return "PROXY {proxy_host}:{proxy_port}";
        }}
    }}
    return "DIRECT";
}}
"#,
        entries = entries,
        proxy_host = proxy_host,
        proxy_port = proxy_port,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_valid_js_shape() {
        let pac = render_pac(&["claude.ai".to_string()], "127.0.0.1", 8443);
        assert!(pac.contains("function FindProxyForURL"));
        assert!(pac.contains("\"claude.ai\""));
        assert!(pac.contains("PROXY 127.0.0.1:8443"));
        assert!(pac.contains("return \"DIRECT\""));
    }

    #[test]
    fn escapes_domains_that_could_otherwise_break_out_of_the_string_literal() {
        let malicious = r#"evil.com","x":true,//"#.to_string();
        let pac = render_pac(&[malicious], "127.0.0.1", 8443);
        // The quote/backslash-bearing entry must appear only as an escaped
        // JSON/JS string literal, never as raw unescaped script text that
        // could terminate the string and inject a new statement.
        assert!(pac.contains(r#""evil.com\",\"x\":true,//""#));
    }
}
