[package]
name = "agent-ca"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true

[dependencies]
rcgen = { workspace = true }
time = { version = "0.3", features = ["std"] }
thiserror = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = [
    "Win32_Security_Cryptography",
    "Win32_Foundation",
] }
serde_json = { workspace = true }
