global:
  scrape_interval: 15s

scrape_configs:
  - job_name: ai-spm-api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]

  - job_name: kong
    static_configs:
      - targets: ["kong:8001"]
