<#
.SYNOPSIS
  Builds a production release and packages it into dist\ as a versioned zip
  (the .msi installer + INSTALL-NOTES.txt) - the standing convention so a
  "give me the current build" request always produces the same
  self-contained deliverable in the same place.

.DESCRIPTION
  1. cargo build --release --workspace
  2. cargo wix -p agent   (produces target\wix\agent-<version>-x86_64.msi)
  3. Copies the .msi and packaging\INSTALL-NOTES.txt into dist\
  4. Zips them into dist\AI-SPM-DLP-Agent-<version>.zip

  dist\ is gitignored (it's build output, regenerated by this script);
  packaging\INSTALL-NOTES.txt is the tracked, hand-maintained source of the
  usage notes bundled with every build - edit it there, not in dist\.

  Resolves the WiX Toolset bin directory from the machine-level WIX
  environment variable (not $env:WIX) - a shell session started before the
  WiX Toolset was installed won't have picked up the machine env var
  refresh, but reading it via [System.Environment]::GetEnvironmentVariable
  works regardless of when the current session started.
#>

$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

Write-Host "== Building release binaries ==" -ForegroundColor Cyan
cargo build --release --workspace
if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }

Write-Host "== Resolving WiX Toolset location ==" -ForegroundColor Cyan
$wixRoot = [System.Environment]::GetEnvironmentVariable("WIX", "Machine")
if (-not $wixRoot) {
    throw "WIX environment variable not set - install the WiX Toolset v3 first (winget install --id WiXToolset.WiXToolset)."
}
$wixBin = Join-Path $wixRoot "bin"

Write-Host "== Building the MSI (cargo wix) ==" -ForegroundColor Cyan
cargo wix -p agent -b $wixBin
if ($LASTEXITCODE -ne 0) { throw "cargo wix failed" }

$msi = Get-ChildItem "$projectRoot\target\wix\*.msi" | Select-Object -First 1
if (-not $msi) { throw "no .msi found under target\wix after cargo wix" }

$versionMatch = Select-String -Path "$projectRoot\Cargo.toml" -Pattern '^version\s*=\s*"([^"]+)"' | Select-Object -First 1
$version = $versionMatch.Matches[0].Groups[1].Value

Write-Host "== Assembling dist\ (version $version) ==" -ForegroundColor Cyan
$dist = Join-Path $projectRoot "dist"
New-Item -ItemType Directory -Path $dist -Force | Out-Null
Copy-Item $msi.FullName -Destination $dist -Force
Copy-Item (Join-Path $projectRoot "packaging\INSTALL-NOTES.txt") -Destination $dist -Force

$zip = Join-Path $dist "AI-SPM-DLP-Agent-$version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $dist $msi.Name), (Join-Path $dist "INSTALL-NOTES.txt") -DestinationPath $zip

Write-Host ""
Write-Host "Done. Package: $zip" -ForegroundColor Green
Get-Item $zip | Select-Object FullName, @{Name = "SizeMB"; Expression = { [math]::Round($_.Length / 1MB, 2) } }
