<#
.SYNOPSIS
  Builds a production release and packages it into dist\ as a versioned zip
  (the .msi installer + INSTALL-NOTES.txt) - the standing convention so a
  "give me the current build" request always produces the same
  self-contained deliverable in the same place.

.DESCRIPTION
  1. cargo build --release --workspace
  2. cargo wix -p agent   (produces target\wix\agent-<version>-x86_64.msi)
  3. Copies the .msi and packaging\INSTALL-NOTES.txt into dist\
  4. Zips them into dist\AI-SPM-DLP-Agent-<version>.zip

  dist\ is gitignored (it's build output, regenerated by this script);
  packaging\INSTALL-NOTES.txt is the tracked, hand-maintained source of the
  usage notes bundled with every build - edit it there, not in dist\.

  Resolves the WiX Toolset bin directory three ways, in order, since not
  every install method sets things up identically (this was found the hard
  way: the CI job's `choco install wixtoolset` didn't leave things
  resolvable the same way a local winget install did):
    1. The machine-level WIX environment variable, read directly via
       [System.Environment]::GetEnvironmentVariable(...,"Machine") rather
       than $env:WIX - a shell session started before the WiX Toolset was
       installed won't have picked up the machine env var refresh, but the
       direct registry read works regardless of when the session started.
    2. candle.exe already on PATH.
    3. A direct filesystem search under Program Files for a WiX Toolset
       install (covers install methods that don't set the WIX env var).
#>

$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $projectRoot

Write-Host "== Building release binaries ==" -ForegroundColor Cyan
cargo build --release --workspace
if ($LASTEXITCODE -ne 0) { throw "cargo build failed" }

Write-Host "== Resolving WiX Toolset location ==" -ForegroundColor Cyan
$wixBin = $null

$wixRoot = [System.Environment]::GetEnvironmentVariable("WIX", "Machine")
if ($wixRoot -and (Test-Path (Join-Path $wixRoot "bin\candle.exe"))) {
    $wixBin = Join-Path $wixRoot "bin"
    Write-Host "Found via WIX environment variable: $wixBin"
}

if (-not $wixBin) {
    $candleOnPath = Get-Command candle.exe -ErrorAction SilentlyContinue
    if ($candleOnPath) {
        $wixBin = Split-Path $candleOnPath.Source -Parent
        Write-Host "Found via PATH: $wixBin"
    }
}

if (-not $wixBin) {
    $found = Get-ChildItem -Path "C:\Program Files*\WiX Toolset*\bin\candle.exe" -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($found) {
        $wixBin = Split-Path $found.FullName -Parent
        Write-Host "Found via filesystem search: $wixBin"
    }
}

if (-not $wixBin) {
    throw "Could not locate the WiX Toolset (candle.exe/light.exe) via the WIX environment variable, PATH, or Program Files - install the WiX Toolset v3 first (winget install --id WiXToolset.WiXToolset, or choco install wixtoolset)."
}

Write-Host "== Building the MSI (cargo wix) ==" -ForegroundColor Cyan
cargo wix -p agent -b $wixBin
if ($LASTEXITCODE -ne 0) { throw "cargo wix failed" }

$msi = Get-ChildItem "$projectRoot\target\wix\*.msi" | Select-Object -First 1
if (-not $msi) { throw "no .msi found under target\wix after cargo wix" }

$versionMatch = Select-String -Path "$projectRoot\Cargo.toml" -Pattern '^version\s*=\s*"([^"]+)"' | Select-Object -First 1
$version = $versionMatch.Matches[0].Groups[1].Value

Write-Host "== Assembling dist\ (version $version) ==" -ForegroundColor Cyan
$dist = Join-Path $projectRoot "dist"
New-Item -ItemType Directory -Path $dist -Force | Out-Null
Copy-Item $msi.FullName -Destination $dist -Force
Copy-Item (Join-Path $projectRoot "packaging\INSTALL-NOTES.txt") -Destination $dist -Force

$zip = Join-Path $dist "AI-SPM-DLP-Agent-$version.zip"
if (Test-Path $zip) { Remove-Item $zip -Force }
Compress-Archive -Path (Join-Path $dist $msi.Name), (Join-Path $dist "INSTALL-NOTES.txt") -DestinationPath $zip

Write-Host ""
Write-Host "Done. Package: $zip" -ForegroundColor Green
Get-Item $zip | Select-Object FullName, @{Name = "SizeMB"; Expression = { [math]::Round($_.Length / 1MB, 2) } }
